version: '3.1'
# docker-compose up --build -d
# docker-compose down -v --rmi local

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kberl    
    networks: # Conectamos nuestro contenedor a nuestra Network
      - custom-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: itvod_mx
      ME_CONFIG_BASICAUTH_PASSWORD: itvod_mx
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: kberl
      
    depends_on:
      - mongo_db
    networks: # Conectamos nuestro contenedor a nuestra Network
      - custom-network

  flask-app:
    build: ./
    container_name: flask-app
    ports:
      - 5000:5000
    depends_on:
      - mongo_db
    links:
      - mongo_db
    networks: # Conectamos nuestro contenedor a nuestra Network
      - custom-network

# Definimos una Network personalizada donde podamos conectar todos
# nuestro contenedores, para que de esta manera todos nuestros contenedores
# puedan comunicarse entre sí.
networks: 
    custom-network:
      name: custom-network
      driver: bridge
